# Generated by Django 4.2.2 on 2024-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('self_employed', models.CharField(max_length=3)),
                ('family_history', models.CharField(max_length=3)),
                ('treatment', models.CharField(max_length=3)),
                ('work_interfere', models.CharField(max_length=20)),
                ('no_employees', models.CharField(max_length=20)),
                ('remote_work', models.CharField(max_length=3)),
                ('tech_company', models.CharField(max_length=3)),
                ('benefits', models.CharField(max_length=20)),
                ('care_options', models.CharField(max_length=20)),
                ('wellness_program', models.CharField(max_length=20)),
                ('seek_help', models.CharField(max_length=20)),
                ('anonymity', models.CharField(max_length=20)),
                ('leave', models.CharField(max_length=20)),
                ('mental_health_consequence', models.CharField(max_length=20)),
                ('phys_health_consequence', models.CharField(max_length=20)),
                ('coworkers', models.CharField(max_length=20)),
                ('supervisor', models.CharField(max_length=20)),
                ('mental_health_interview', models.CharField(max_length=20)),
                ('phys_health_interview', models.CharField(max_length=20)),
                ('mental_vs_physical', models.CharField(max_length=20)),
                ('obs_consequence', models.CharField(max_length=3)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
