# Generated by Django 4.2.2 on 2024-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_surveyresponse_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='anonymity',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='benefits',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='care_options',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='coworkers',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='family_history',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='leave',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='mental_health_consequence',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='mental_health_interview',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='mental_vs_physical',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='no_employees',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='obs_consequence',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='phys_health_consequence',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='phys_health_interview',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='remote_work',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='seek_help',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='self_employed',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='supervisor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='tech_company',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='treatment',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='wellness_program',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='work_interfere',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
